name: Java CI with Maven

on:
  push:
    branches: [ "fix-vipstests-github-actions" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # - uses: browser-actions/setup-chrome@v1
    # - run: chrome --version
    - uses: actions/checkout@v3

    - name: Install prerequisites (chromedriver)
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk2.0-0 chromium-chromedriver
        chromedriver --version

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      # Skip VipsSeleniumTests for now because it is failing on GitHub Actions
      run: mvn -Djavacpp.platform.linux-x86_64 -B package -P integrationtests --file pom.xml
