name: Java CI with Maven

on:
  push:
    branches: [ "fix-vipstests-github-actions" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
#        os: [ubuntu-latest, macos-latest, windows-latest]
        os: [windows-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Install prerequisites (libgtk on ubuntu)
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get update
            sudo apt-get install -y libgtk2.0-0 
        fi
      shell: bash
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package -P integrationtests --file pom.xml